[workspace]
members = ["programs/nft-staking"]

[registry]
url = "https://anchor.projectserum.com"

[provider]
cluster = "devnet"
wallet = "./devnet-wallet.json"

[programs.localnet]
nft_staking = "paramKFFuRPLVXZWjDRbnk5xKemduYZUW2BqUp7xZD3"

[scripts]
test = "ts-mocha --path tsconfig.json -t 1000000 tests/nft-staking/*.ts"
